#!/bin/bash
# options
menu(){
im="zenity --list --radiolist --title=\"Change Icon\" --text=\"<b>Select icon to use:</b>\" --width 270 --height 170"
im=$im" --column=\"☑\" --column \"Options\" --column \"Description\" "
im=$im"FALSE \"Light\" \"Icon for dark panels\" "
im=$im"FALSE \"Dark\" \"Icon for light panels\" "
im=$im"FALSE \"Color\" \"Icon for all panels\" "
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep "Light" > /dev/null
then
	cp -f /usr/local/indicator-hostsblock/hostsblock-dark.png /usr/local/indicator-hostsblock/hostsblock.png
fi
if echo $choice | grep "Dark" > /dev/null
then
	cp -f /usr/local/indicator-hostsblock/hostsblock-light.png /usr/local/indicator-hostsblock/hostsblock.png
fi
if echo $choice | grep "Color" > /dev/null
then
	cp -f /usr/local/indicator-hostsblock/hostsblock-color.png /usr/local/indicator-hostsblock/hostsblock.png
fi
}
menu
option
