#!/bin/bash
# get password
sudo_password=$(gksudo --print-pass --description="HostsBlock" --message="Provide permission to make system changes: Type your password or press Cancel." -- : 2>/dev/null)
# check for null entry or cancellation
if [[ ${?} != 0 || -z ${sudo_password} ]]
then
	exit 4
fi
if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
then
	exit 4
fi
# options
menu(){
im="zenity --list --checklist --title=\"HostsBlock Editor\" --text=\"<b>Select file(s) to edit:</b>\" --width 370 --height 190"
im=$im" --column=\"☑\" --column \"Filename\" --column \"Location\" "
im=$im"FALSE \"hosts.block\" \"/etc/hosts.block\" "
im=$im"FALSE \"hostsblock.conf\" \"/usr/share/hostsblock/hostsblock.conf\" "
im=$im"FALSE \"black.list\" \"/usr/share/hostsblock/black.list\" "
im=$im"FALSE \"white.list\" \"/usr/share/hostsblock/white.list\" "
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep "hosts.block" > /dev/null
then
	sudo -Sp '' gedit "/etc/hosts.block" <<<"${sudo_password}" &
fi
if echo $choice | grep "hostsblock.conf" > /dev/null
then
	sudo -Sp '' gedit "/usr/share/hostsblock/hostsblock.conf" <<<"${sudo_password}" &
fi
if echo $choice | grep "black.list" > /dev/null
then
	sudo -Sp '' gedit "/usr/share/hostsblock/black.list" <<<"${sudo_password}" &
fi
if echo $choice | grep "white.list" > /dev/null
then
	sudo -Sp '' gedit "/usr/share/hostsblock/white.list" <<<"${sudo_password}" &
fi
}
menu
option
