#!/bin/bash
# options
menu(){
im="zenity --list --checklist --title=\"HostsBlock Editor\" --text=\"<b>Select file(s) to edit:</b>\" --width 420 --height 150"
im=$im" --column=\"☑\" --column \"Filename\" --column \"Location\" "
im=$im"FALSE \"user.deny.list\" \"~/.local/share/indicator-hostsblock/user.deny.list\" "
im=$im"FALSE \"user.allow.list\" \"~/.local/share/indicator-hostsblock/user.allow.list\" "
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep "user.deny.list" > /dev/null
then
	if [ -f $HOME/.local/share/indicator-hostsblock/user.deny.list ]
	then
		xdg-open $HOME/.local/share/indicator-hostsblock/user.deny.list &
	else
		zenity --question --title="user.deny.list doesn't exist" --text="Would you like to create \"$HOME/.local/share/indicator-hostsblock/user.deny.list\" now?"
		if [ $? = 0 ]
		then
			if [ ! -d $HOME/.local/share/indicator-hostsblock/ ]
			then
				mkdir $HOME/.local/share/indicator-hostsblock/
			else
				touch $HOME/.local/share/indicator-hostsblock/user.deny.list
				xdg-open $HOME/.local/share/indicator-hostsblock/user.deny.list &
			fi
		fi
	fi
fi
if echo $choice | grep "user.allow.list" > /dev/null
then
	if [ -f $HOME/.local/share/indicator-hostsblock/user.allow.list ]
	then
		xdg-open $HOME/.local/share/indicator-hostsblock/user.allow.list &
	else
		zenity --question --title="user.allow.list doesn't exist" --text="Would you like to create \"$HOME/.local/share/indicator-hostsblock/user.allow.list\" now?"
		if [ $? = 0 ]
		then
			if [ ! -d $HOME/.local/share/indicator-hostsblock/ ]
			then
				mkdir $HOME/.local/share/indicator-hostsblock/
			else
				touch $HOME/.local/share/indicator-hostsblock/user.allow.list
				xdg-open $HOME/.local/share/indicator-hostsblock/user.allow.list &
			fi
		fi
	fi
fi
}
menu
option
