#!/bin/bash
log_file="/var/log/hostsblock.log"
# check if log does not exist
if [[ ! -f "$log_file" ]]
then
	if [[ -L "$log_file" ]]
	then
		echo "Last: None"
	else
		echo "Last: None"
	fi
# if exists
else
	echo "Last: `cat "/var/log/hostsblock.log" | grep 'Hostsblock completed at ' | awk -F ' at ' '{print $2}'`"
fi
