#!/bin/bash
# options
menu(){
im="zenity --list --checklist --title=\"HostsBlock Viewer\" --text=\"<b>Select file(s) to view:</b>\" --width 480 --height 230"
im=$im" --column=\"☑\" --column \"Filename\" --column \"Location\" "
im=$im"FALSE \"hostsblock.conf(full)\" \"/etc/hostsblock/hostsblock.conf (full)\" "
im=$im"FALSE \"hostsblock.conf(extract)\" \"/etc/hostsblock/hostsblock.conf (extract)\" "
im=$im"FALSE \"black.list\" \"/etc/hostsblock/black.list\" "
im=$im"FALSE \"white.list\" \"/etc/hostsblock/white.list\" "
im=$im"FALSE \"user.deny.list\" \"~/.local/share/indicator-hostsblock/user.deny.list\" "
im=$im"FALSE \"user.allow.list\" \"~/.local/share/indicator-hostsblock/user.allow.list\" "
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep "hostsblock.conf(full)" > /dev/null
then
	zenity --text-info --filename="/etc/hostsblock/hostsblock.conf" --title="hostsblock.conf - full (view only)" --width 980 --height 680 &
fi
if echo $choice | grep "hostsblock.conf(extract)" > /dev/null
then
	cp '/etc/hostsblock/hostsblock.conf' '/tmp/extract-hostsblock.conf'
	sed -i 's/^# .*$//g' '/tmp/extract-hostsblock.conf'
	sed -i "s/^### .*$//g" "/tmp/extract-hostsblock.conf"
	sed -i "/^\s*$/d" "/tmp/extract-hostsblock.conf"
	sed -i "s/^##/\n##/g" "/tmp/extract-hostsblock.conf"
	zenity --text-info --filename="/tmp/extract-hostsblock.conf" --title="hostsblock.conf - extract (view only)" --width 980 --height 680 &
fi
if echo $choice | grep "black.list" > /dev/null
then
	zenity --text-info --filename="/etc/hostsblock/black.list" --title="black.list (view only)" --width 300 --height 600 &
fi
if echo $choice | grep "white.list" > /dev/null
then
	zenity --text-info --filename="/etc/hostsblock/white.list" --title="white.list (view only)" --width 300 --height 500 &
fi
if echo $choice | grep "user.deny.list" > /dev/null
then
	if [ -f $HOME/.local/share/indicator-hostsblock/user.deny.list ]
	then
		zenity --text-info --filename="$HOME/.local/share/indicator-hostsblock/user.deny.list" --title="user.deny.list (view only)" --width 300 --height 600 &
	else
		notify-send "user.deny.list does not exist" -i gtk-dialog-info -t 1000 -u normal &
	fi
fi
if echo $choice | grep "user.allow.list" > /dev/null
then
	if [ -f $HOME/.local/share/indicator-hostsblock/user.allow.list ]
	then
		zenity --text-info --filename=$HOME/.local/share/indicator-hostsblock/user.allow.list --title="user.allow.list (view only)" --width 300 --height 600 &
	else
		notify-send "user.allow.list does not exist" -i gtk-dialog-info -t 1000 -u normal &
	fi
fi
}
menu
option
