#!/bin/bash
# options
menu(){
im="zenity --list --checklist --title=\"HostsBlock Viewer\" --text=\"Please select one or more files to view:\" --width 400 --height 240"
im=$im" --column=\"☑\" --column \"Filename\" --column \"Location\" "
im=$im"FALSE \"hostsblock.log\" \"/var/log/hostsblock.log\" "
im=$im"FALSE \"hosts.block\" \"/etc/hosts.block\" "
im=$im"FALSE \"hostsblock.conf\" \"/etc/hosts.block/hostsblock.conf\" "
im=$im"FALSE \"black.list\" \"/etc/hosts.block/black.list\" "
im=$im"FALSE \"white.list\" \"/etc/hosts.block/white.list\" "
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep "hostsblock.log" > /dev/null
then
	zenity --text-info --filename=/var/log/hostsblock.log --title="hostsblock.log (view only)" --width 680 --height 580 &
fi
if echo $choice | grep "hosts.block" > /dev/null
then
	zenity --text-info --filename=/etc/hosts.block --title="hosts.block (view only)" --width 600 --height 800 &
fi
if echo $choice | grep "hostsblock.conf" > /dev/null
then
	zenity --text-info --filename=/etc/hostsblock/hostsblock.conf --title="hostsblock.conf (view only)" --width 980 --height 680 &
fi
if echo $choice | grep "black.list" > /dev/null
then
	zenity --text-info --filename=/etc/hostsblock/black.list --title="black.list (view only)" --width 300 --height 600 &
fi
if echo $choice | grep "white.list" > /dev/null
then
	zenity --text-info --filename=/etc/hostsblock/white.list --title="white.list (view only)" --width 300 --height 500 &
fi
}
menu
option
if test ${#choice} -gt 0
then
	echo "Completed"
fi
