#! /bin/sh
### BEGIN INIT INFO
# Provides:       kwakd
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    A web server serving blank html pages
### END INIT INFO

# /etc/init.d/kwakd

# START section imported from /etc/init.d/dnsmaq
# Provide skeleton LSB log functions for backports which don't have LSB functions.
if [ -f /lib/lsb/init-functions ]; then
         . /lib/lsb/init-functions
else
         log_warning_msg () {
            echo "${@}."
         }
         log_success_msg () {
            echo "${@}."
         }
         log_daemon_msg () {
            echo -n "${1}: $2"
         }
	 log_end_msg () {
            if [ $1 -eq 0 ]; then
              echo "."
            elif [ $1 -eq 255 ]; then
              /bin/echo -e " (warning)."
            else
              /bin/echo -e " failed!"
            fi
         }
fi
# END section imported from /etc/init.d/dnsmaq

case "$1" in
  start)
    echo "Starting kwakd"
    if [ ! "$(pidof kwakd)" ]; then
    /usr/bin/kwakd -b -p 80
    else
    echo "kwakd is already running!"
    fi 
    ;;
  stop)
    echo "Stopping kwakd"
    if [ "$(pidof kwakd)" ]; then
    killall kwakd
    echo "Stopped."
    else
    echo "kwakd is not running"
    fi 
    ;;
  restart|force-reload)				# START section added to meet debian lintian requirements
    echo "Stopping kwakd"
    if [ "$(pidof kwakd)" ]; then
    killall kwakd
    echo "Stopped."
    echo "Starting kwakd"
    /usr/bin/kwakd -b -p 80
    else
    echo "kwakd is not running"
    fi
    ;;						# END section added debian to meet lintian requirements
  *)
    echo "Usage: /etc/init.d/kwakd {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
