#!/bin/bash
cuser="${SUDO_USER:-$USER}"
check_hourly="$(ls /etc/cron.hourly | grep hostsblock-launcher)"
check_daily="$(ls /etc/cron.daily | grep hostsblock-launcher)"
check_weekly="$(ls /etc/cron.weekly | grep hostsblock-launcher)"
check_monthly="$(ls /etc/cron.monthly | grep hostsblock-launcher)"
if [ "$check_hourly" = hostsblock-launcher ]
then
	echo "HostsBlock is auto-updated hourly." > "/home/"$cuser"/.hostsblock-scheduler.txt"
else
if [ "$check_daily" = hostsblock-launcher ]
then
	echo "HostsBlock is auto-updated daily." > "/home/"$cuser"/.hostsblock-scheduler.txt"
else
if [ "$check_weekly" = hostsblock-launcher ]
then
	echo "HostsBlock is auto-updated weekly." > "/home/"$cuser"/.hostsblock-scheduler.txt"
else
if [ "$check_monthly" = hostsblock-launcher ]
then
	echo "HostsBlock is auto-updated monthly." > "/home/"$cuser"/.hostsblock-scheduler.txt"
else
	echo "HostsBlock is NOT auto-updated." > "/home/"$cuser"/.hostsblock-scheduler.txt"
fi
fi
fi
fi
auto_update="$(cat /home/"$cuser"/.hostsblock-scheduler.txt)"
zenity --question --text "$auto_update\n\nWould you like to change it?"
if [ $? = 0 ];
then
# password
sudo_password="$(gksudo --print-pass --description 'hostsblock' -- : 2>/dev/null)"
# check for null entry or cancellation
	if [[ ${?} != 0 || -z ${sudo_password} ]]
	then
		exit 4
	fi
	if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
	then
		exit 4
	fi
else
	exit 4
fi
# options
menu(){
im="zenity --list --radiolist --title=\"HostsBlock Scheduler\" --width 400 --height 210"
im=$im" --column=\" \" --column \"Options\" --column \"Description\" "
im=$im"FALSE \"Hourly\" \"HostsBlock auto-updates every hour\" "
im=$im"FALSE \"Daily\" \"HostsBlock auto-updates every day\" "
im=$im"TRUE \"Weekly\" \"HostsBlock auto-updates every week\" "
im=$im"FALSE \"Monthly\" \"HostsBlock auto-updates every month\" "
im=$im"FALSE \"None\" \"HostsBlock DOES NOT auto-update\" "
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep "Hourly" > /dev/null
then
	sudo -Sp '' sudo rm /etc/cron.hourly/hostsblock-launcher /etc/cron.daily/hostsblock-launcher /etc/cron.weekly/hostsblock-launcher /etc/cron.monthly/hostsblock-launcher <<<"${sudo_password}"
	sudo -Sp '' sudo ln -sf "/usr/local/hostsblock-gui/hostsblock-launcher" "/etc/cron.hourly/hostsblock-launcher" <<<"${sudo_password}"
	sudo -Sp '' sudo -H -u "$cuser" notify-send "HostsBlock will now be automatically updated every hour" -i gtk-dialog-info -t 1000 -u normal <<<"${sudo_password}" &
fi
if echo $choice | grep "Daily" > /dev/null
then
	sudo -Sp '' sudo rm /etc/cron.hourly/hostsblock-launcher /etc/cron.daily/hostsblock-launcher /etc/cron.weekly/hostsblock-launcher /etc/cron.monthly/hostsblock-launcher <<<"${sudo_password}"
	sudo -Sp '' sudo ln -sf "/usr/local/hostsblock-gui/hostsblock-launcher" "/etc/cron.daily/hostsblock-launcher" <<<"${sudo_password}"
	sudo -Sp '' sudo -H -u "$cuser" notify-send "HostsBlock will now be automatically updated every day" -i gtk-dialog-info -t 1000 -u normal <<<"${sudo_password}" &
fi
if echo $choice | grep "Weekly" > /dev/null
then
	sudo -Sp '' sudo rm /etc/cron.hourly/hostsblock-launcher /etc/cron.daily/hostsblock-launcher /etc/cron.weekly/hostsblock-launcher /etc/cron.monthly/hostsblock-launcher <<<"${sudo_password}"
	sudo -Sp '' sudo ln -sf "/usr/local/hostsblock-gui/hostsblock-launcher" "/etc/cron.weekly/hostsblock-launcher" <<<"${sudo_password}"
	sudo -Sp '' sudo -H -u "$cuser" notify-send "HostsBlock will now be automatically updated every week" -i gtk-dialog-info -t 1000 -u normal <<<"${sudo_password}" &
fi
if echo $choice | grep "Monthly" > /dev/null
then
	sudo -Sp '' sudo rm /etc/cron.hourly/hostsblock-launcher /etc/cron.daily/hostsblock-launcher /etc/cron.weekly/hostsblock-launcher /etc/cron.monthly/hostsblock-launcher <<<"${sudo_password}"
	sudo -Sp '' sudo ln -sf "/usr/local/hostsblock-gui/hostsblock-launcher" "/etc/cron.monthly/hostsblock-launcher" <<<"${sudo_password}"
	sudo -Sp '' sudo -H -u "$cuser" notify-send "HostsBlock will now be automatically updated every month" -i gtk-dialog-info -t 1000 -u normal <<<"${sudo_password}" &
fi
if echo $choice | grep "None" > /dev/null
then
	sudo -Sp '' sudo rm /etc/cron.hourly/hostsblock-launcher /etc/cron.daily/hostsblock-launcher /etc/cron.weekly/hostsblock-launcher /etc/cron.monthly/hostsblock-launcher <<<"${sudo_password}"
	sudo -Sp '' sudo -H -u "$cuser" notify-send "HostsBlock will not be automatically updated from now on." -i gtk-dialog-info -t 1000 -u normal <<<"${sudo_password}" &
fi
}
menu
option
if test ${#choice} -gt 0
then
	echo "Scheduling completed"
fi
