#!/bin/bash
# notify
notify-send "Hostsblock is checking if there are any updates..." -i gtk-dialog-info -t 1000 -u normal &
# check updates
/usr/local/hostsblock-gui/hostsblock-check-updates -v 3 &>/tmp/hostsblock-check-updates.log
# append date and time stamp to log
cat <<EOF >> /tmp/hostsblock-check-updates.log
Hostsblock checked updates at `date +'%d/%m/%Y %H:%M'`
EOF
# changes
cat "/tmp/hostsblock-check-updates.log" | \
grep "\[WARN\] FAILED to refresh\/download blocklist " | \
sed -e 's/^\[WARN\] FAILED to refresh\/download blocklist //g' -e 's/\?hostformat=hosts&mimetype=plaintext//g' -e 's/\.$//g' -e 's/^http/• http/g' > "/tmp/hostsblock-updates.log"
changes=$(grep http /tmp/hostsblock-updates.log)
# no changes
if [ -z "$changes" ]
then
	notify-send "Hostsblock found no updates; exiting..." -i gtk-dialog-info -t 1000 -u normal &
	exit
else
	zenity --question --text "Hostsblock found changes in:\n<i>$changes</i>\n\nWould you like to update now?"
	if [ $? = 0 ]
	then
# password
sudo_password="$(gksudo --print-pass --description 'hostsblock' -- : 2>/dev/null)"
# check for null entry or cancellation
		if [[ ${?} != 0 || -z ${sudo_password} ]]
		then
			exit 4
		fi
		if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
		then
			exit 4
		fi
# notify
		notify-send "Hostsblock is applying updates..." -i gtk-dialog-info -t 1000 -u normal &
# proceed to update
		sudo -Sp '' sudo /etc/hostsblock/hostsblock.sh -v 3 &>/tmp/hostsblock.log  <<<"${sudo_password}"
		sudo -Sp '' sudo chmod a+w /tmp/hostsblock.log  <<<"${sudo_password}"
# append date and time stamp to log
cat <<EOF >> /tmp/hostsblock.log
Hostsblock completed at `date +'%d/%m/%Y %H:%M'`
EOF
# option to view log
new_update="$(cat /tmp/hostsblock.log | grep 'Hostsblock completed at ' | awk -F ' at ' '{print $2}')"
		zenity --question --text "Hostsblock updated at <b><i>$new_update</i></b>\n\nWould you like to view the log file now?"
			if [ $? = 0 ]
			then
# display log
			zenity --text-info --filename=/tmp/hostsblock.log --width 680 --height 680
			fi
	fi
fi
