#!/bin/bash
# launch hostsblock with verbosity level 3, and create log
"/usr/share/indicator-hostsblock/hostsblock.sh" -v 3 &>"/tmp/hostsblock.log"
# append date and time stamp to log
echo "Hostsblock completed on `date +'%a %d %b'` `date +'%H:%M'`" >> "/tmp/hostsblock.log"
# make log file open for all
chmod a+w "/tmp/hostsblock.log"
# backup log
cp -f "/tmp/hostsblock.log" "/usr/share/indicator-hostsblock/hostsblock.log"
# create cumulative log
grep "Hostsblock completed on " "/usr/share/indicator-hostsblock/hostsblock.log" > "/tmp/hostsblock-cumulative.log"
grep " urls redirected to " "/usr/share/indicator-hostsblock/hostsblock.log" >> "/tmp/hostsblock-cumulative.log"
sed -i 's/Hostsblock completed on [A-Z][a-z][a-z] //g' "/tmp/hostsblock-cumulative.log"
sed -i 's/\[INFO\] \/etc\/hosts\.block: //g' "/tmp/hostsblock-cumulative.log"
sed -i 's/ redirected to 0\.0\.0\.0\./ redirected/g' "/tmp/hostsblock-cumulative.log"
sed -i 's/ redirected to 0\.0\.0\.0\./ redirected/g' "/tmp/hostsblock-cumulative.log"
cat "/tmp/hostsblock-cumulative.log" | tr '\n' '\t' > "/tmp/hostsblock-cumulative.txt"
mv "/tmp/hostsblock-cumulative.txt" "/tmp/hostsblock-cumulative.log"
if [[ ! -f "/usr/share/indicator-hostsblock/hostsblock-cumulative.log" ]]
then
	touch "/usr/share/indicator-hostsblock/hostsblock-cumulative.log"
	chmod a+w "/usr/share/indicator-hostsblock/hostsblock-cumulative.log"
fi
cat "/tmp/hostsblock-cumulative.log" >> "/usr/share/indicator-hostsblock/hostsblock-cumulative.log"
lines=$(wc -l "/usr/share/indicator-hostsblock/hostsblock-cumulative.log" | awk '{print $1}')
if [ $lines -gt 99 ]
then
	sed -i -e "1,3d" "/usr/share/indicator-hostsblock/hostsblock-cumulative.log"
fi
# create message
changes=$(grep -c "CHANGES FOUND" "/tmp/hostsblock.log")
if [ "$changes" -gt 0 ]
then
	echo "Hostsblock has just checked and updated $changes blocklist(s)" > "/tmp/hostsblock-launcher-message.txt"
# notify user(s)
	xuser=$(who | grep " \:[0-9]" | awk '{print $1}')
	xdisplay=$(who | grep " \:[0-9]" | awk '{print $5}' | sed "s/[(|)]//g")
	message=$(cat "/tmp/hostsblock-launcher-message.txt")
	echo "$xuser" > "/tmp/xusers.txt"
	echo "$xdisplay" > "/tmp/xdisplays.txt"
	while read -r -u3 xuser; read -r -u4 xdisplay
	do
		DISPLAY="$xdisplay" XAUTHORITY="/home/"$xuser"/.Xauthority" su "$xuser" -c "notify-send '$message' -i gtk-dialog-info -t 1000 -u normal" &
	done 3<"/tmp/xusers.txt" 4<"/tmp/xdisplays.txt"
else
	echo "Hostsblock has just checked and found no updates" > "/tmp/hostsblock-launcher-message.txt"
# notify user(s)
	xuser=$(who | grep " \:[0-9]" | awk '{print $1}')
	xdisplay=$(who | grep " \:[0-9]" | awk '{print $5}' | sed "s/[(|)]//g")
	message=$(cat "/tmp/hostsblock-launcher-message.txt")
	echo "$xuser" > "/tmp/xusers.txt"
	echo "$xdisplay" > "/tmp/xdisplays.txt"
	while read -r -u3 xuser; read -r -u4 xdisplay
	do
		DISPLAY="$xdisplay" XAUTHORITY="/home/"$xuser"/.Xauthority" su "$xuser" -c "notify-send '$message' -i gtk-dialog-info -t 1000 -u normal" &
	done 3<"/tmp/xusers.txt" 4<"/tmp/xdisplays.txt"
fi
