#!/bin/bash
# launch hostsblock with verbosity level 3, and create log
"/usr/share/indicator-hostsblock/hostsblock.sh" -v 3 &>"/tmp/hostsblock.log"
# append date and time stamp to log
echo "Hostsblock completed on `date +'%a %d %b'` `date +'%H:%M'`" >> "/tmp/hostsblock.log"
# make log file open for all
chmod a+w "/tmp/hostsblock.log"
# backup log
cp -f "/tmp/hostsblock.log" "/usr/share/indicator-hostsblock/hostsblock.log"
# create history log
grep "Hostsblock completed on " "/usr/share/indicator-hostsblock/hostsblock.log" > "/tmp/hostsblock-history-new.log"
grep " urls redirected to " "/usr/share/indicator-hostsblock/hostsblock.log" >> "/tmp/hostsblock-history-new.log"
sed -i 's/Hostsblock completed on [A-Z][a-z][a-z] //g' "/tmp/hostsblock-history-new.log"
sed -i 's/\[INFO\] \/etc\/hosts\.block: //g' "/tmp/hostsblock-history-new.log"
sed -i 's/ redirected to 0\.0\.0\.0\./ redirected/g' "/tmp/hostsblock-history-new.log"
sed -i 's/ redirected to 0\.0\.0\.0\./ redirected/g' "/tmp/hostsblock-history-new.log"
cat "/tmp/hostsblock-history-new.log" | tr '\n' '\t' | sed 's/\t$/\n/g' > "/tmp/hostsblock-history-new.txt"
mv "/tmp/hostsblock-history-new.txt" "/tmp/hostsblock-history-new.log"
chmod a+w "/tmp/hostsblock-history-new.log"
if [[ ! -f "/usr/share/indicator-hostsblock/hostsblock-history.log" ]]
then
	mv "/tmp/hostsblock-history-new.log" "/usr/share/indicator-hostsblock/hostsblock-history.log"
else
	cat "/usr/share/indicator-hostsblock/hostsblock-history.log" >> "/tmp/hostsblock-history-new.log"
	lines=$(wc -l "/tmp/hostsblock-history-new.log" | awk '{print $1}')
	if [ $lines -gt 21 ]
	then
		sed -i '$d' "/tmp/hostsblock-history-new.log"
	fi
	mv "/tmp/hostsblock-history-new.log" "/usr/share/indicator-hostsblock/hostsblock-history.log"
fi
# create message
changes=$(grep -c "CHANGES FOUND" "/tmp/hostsblock.log")
if [ "$changes" -gt 0 ]
then
	echo "Hostsblock has just checked and updated $changes blocklist(s)" > "/tmp/hostsblock-launcher-message.txt"
# notify user(s)
	xuser=$(who | grep " \:[0-9]" | awk '{print $1}')
	xdisplay=$(who | grep " \:[0-9]" | awk '{print $5}' | sed "s/[(|)]//g")
	message=$(cat "/tmp/hostsblock-launcher-message.txt")
	echo "$xuser" > "/tmp/xusers.txt"
	echo "$xdisplay" > "/tmp/xdisplays.txt"
	while read -r -u3 xuser; read -r -u4 xdisplay
	do
		DISPLAY="$xdisplay" XAUTHORITY="/home/"$xuser"/.Xauthority" su "$xuser" -c "notify-send '$message' -i gtk-dialog-info" &
	done 3<"/tmp/xusers.txt" 4<"/tmp/xdisplays.txt"
else
	echo "Hostsblock has just checked and found no updates" > "/tmp/hostsblock-launcher-message.txt"
# notify user(s)
	xuser=$(who | grep " \:[0-9]" | awk '{print $1}')
	xdisplay=$(who | grep " \:[0-9]" | awk '{print $5}' | sed "s/[(|)]//g")
	message=$(cat "/tmp/hostsblock-launcher-message.txt")
	echo "$xuser" > "/tmp/xusers.txt"
	echo "$xdisplay" > "/tmp/xdisplays.txt"
	while read -r -u3 xuser; read -r -u4 xdisplay
	do
		DISPLAY="$xdisplay" XAUTHORITY="/home/"$xuser"/.Xauthority" su "$xuser" -c "notify-send '$message' -i gtk-dialog-info" &
	done 3<"/tmp/xusers.txt" 4<"/tmp/xdisplays.txt"
fi
