#!/bin/bash
# notify
notify-send "HostsBlock is checking if there are any updates..." -i gtk-dialog-info -t 1000 -u normal &
# check updates
"/usr/share/indicator-hostsblock/check-updates" -v 3 &>"/tmp/hostsblock-check-updates.log"
# append date and time stamp to log
cat <<EOF >> "/tmp/hostsblock-check-updates.log"
Hostsblock checked updates at `date +'%d/%m/%Y %H:%M'`
EOF
# changes
cat "/tmp/hostsblock-check-updates.log" | \
grep "\[WARN\] FAILED to refresh\/download blocklist " | \
sed -e "s/^\[WARN\] FAILED to refresh\/download blocklist //g" -e "s/\?hostformat=hosts&mimetype=plaintext//g" -e "s/\.$//g" -e "s/^http/• http/g" > "/tmp/hostsblock-updates.log"
changes=$(grep "http" "/tmp/hostsblock-updates.log")
# no changes
if [ -z "$changes" ]
then
	notify-send "HostsBlock found no updates; exiting..." -i gtk-dialog-info -t 1000 -u normal &
	exit
else
	zenity --question --title="HostsBlock found the following change(s):" --text="<i>$changes</i>\n\n<b>Would you like to update now?</b>" --width 300 --height 300
	if [ $? = 0 ]
	then
# get password
sudo_password=$(gksudo --print-pass --description="HostsBlock" --message="Provide permission to make system changes: Type your password or press Cancel." -- : 2>/dev/null)
# check for null entry or cancellation
		if [[ ${?} != 0 || -z ${sudo_password} ]]
		then
			exit 4
		fi
		if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
		then
			exit 4
		fi
# notify
		notify-send "HostsBlock is applying updates..." -i gtk-dialog-info -t 1000 -u normal &
# proceed to update and make log file open for all
		sudo -Sp '' "/usr/share/indicator-hostsblock/hostsblock.sh" -v 3 &>"/tmp/hostsblock.log" <<<"${sudo_password}"
		sudo -Sp '' chmod a+w "/tmp/hostsblock.log" <<<"${sudo_password}"
# append date and time stamp to log
cat <<EOF >> "/tmp/hostsblock.log"
Hostsblock completed at `date +'%d/%m/%Y %H:%M'`
EOF
# backup log
		sudo -Sp '' cp -f "/tmp/hostsblock.log" "/usr/share/indicator-hostsblock/hostsblock.log" <<<"${sudo_password}"
# option to view log
new_update=$(cat "/tmp/hostsblock.log" | grep "Hostsblock completed at " | awk -F " at " '{print $2}')
		zenity --question --title="HostsBlock Updated" --text="<b><i>$new_update</i></b>\n\nWould you like to view the log file now?"
			if [ $? = 0 ]
			then
# display log
				zenity --text-info --title="hostsblock.log (view only)" --filename="/tmp/hostsblock.log" --width 680 --height 580
			fi
	fi
fi
