#!/bin/bash
check_hourly=$(ls "/etc/cron.hourly" | grep "hostsblock-launcher")
check_daily=$(ls "/etc/cron.daily" | grep "hostsblock-launcher")
check_weekly=$(ls "/etc/cron.weekly" | grep "hostsblock-launcher")
check_monthly=$(ls "/etc/cron.monthly" | grep "hostsblock-launcher")
if [ "$check_hourly" = "hostsblock-launcher" ]
then
	echo "Hourly" > "/tmp/hostsblock-auto-update.txt"
else
	if [ "$check_daily" = "hostsblock-launcher" ]
	then
		echo "Daily" > "/tmp/hostsblock-auto-update.txt"
	else
		if [ "$check_weekly" = "hostsblock-launcher" ]
		then
			echo "Weekly" > "/tmp/hostsblock-auto-update.txt"
		else
			if [ "$check_monthly" = "hostsblock-launcher" ]
			then
				echo "Monthly" > "/tmp/hostsblock-auto-update.txt"
			else
				echo "None" > "/tmp/hostsblock-auto-update.txt"
			fi
		fi
	fi
fi
auto_update=$(cat "/tmp/hostsblock-auto-update.txt")
# options
menu(){
im="zenity --list --radiolist --title=\"HostsBlock Scheduler\" --text=\"Current HostsBlock Auto-Update: <b><i>$auto_update</i></b>\n<b>Select one of the options below to change this:</b>\" --width 380 --height 230"
im=$im" --column=\"☑\" --column \"Options\" --column \"Description\" "
im=$im"FALSE \"Hourly\" \"HostsBlock will auto-update every hour\" "
im=$im"FALSE \"Daily\" \"HostsBlock will auto-update every day\" "
im=$im"FALSE \"Weekly\" \"HostsBlock will auto-update every week\" "
im=$im"FALSE \"Monthly\" \"HostsBlock will auto-update every month\" "
im=$im"FALSE \"None\" \"HostsBlock will not auto-update\" "
}
password(){
# get password
sudo_password=$(gksudo --print-pass --description="HostsBlock" --message="Provide permission to make system changes: Type your password or press Cancel." -- : 2>/dev/null)
# check for null entry or cancellation
if [[ ${?} != 0 || -z ${sudo_password} ]]
then
	exit 4
fi
if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
then
	exit 4
fi
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep -iE "Hourly|Daily|Weekly|Monthly|None" > /dev/null
then
	password
	if echo $choice | grep "Hourly" > /dev/null
	then
		notify-send "HostsBlock will update automatically every hour" -i gtk-dialog-info -t 1000 -u normal &
		sudo -Sp '' rm "/etc/cron.hourly/hostsblock-launcher" "/etc/cron.daily/hostsblock-launcher" "/etc/cron.weekly/hostsblock-launcher" "/etc/cron.monthly/hostsblock-launcher" <<<"${sudo_password}"
		sudo -Sp '' ln -sf "/usr/share/indicator-hostsblock/launcher" "/etc/cron.hourly/hostsblock-launcher" <<<"${sudo_password}"
		"/usr/share/indicator-hostsblock/restart-indicator"
	fi
	if echo $choice | grep "Daily" > /dev/null
	then
		notify-send "HostsBlock will update automatically every day" -i gtk-dialog-info -t 1000 -u normal &
		sudo -Sp '' rm "/etc/cron.hourly/hostsblock-launcher" "/etc/cron.daily/hostsblock-launcher" "/etc/cron.weekly/hostsblock-launcher" "/etc/cron.monthly/hostsblock-launcher" <<<"${sudo_password}"
		sudo -Sp '' ln -sf "/usr/share/indicator-hostsblock/launcher" "/etc/cron.daily/hostsblock-launcher" <<<"${sudo_password}"
		"/usr/share/indicator-hostsblock/restart-indicator"
	fi
	if echo $choice | grep "Weekly" > /dev/null
	then
		notify-send "HostsBlock will update automatically every week" -i gtk-dialog-info -t 1000 -u normal &
		sudo -Sp '' rm "/etc/cron.hourly/hostsblock-launcher" "/etc/cron.daily/hostsblock-launcher" "/etc/cron.weekly/hostsblock-launcher" "/etc/cron.monthly/hostsblock-launcher" <<<"${sudo_password}"
		sudo -Sp '' ln -sf "/usr/share/indicator-hostsblock/launcher" "/etc/cron.weekly/hostsblock-launcher" <<<"${sudo_password}"
		"/usr/share/indicator-hostsblock/restart-indicator"
	fi
	if echo $choice | grep "Monthly" > /dev/null
	then
		notify-send "HostsBlock will update automatically every month" -i gtk-dialog-info -t 1000 -u normal &
		sudo -Sp '' rm "/etc/cron.hourly/hostsblock-launcher" "/etc/cron.daily/hostsblock-launcher" "/etc/cron.weekly/hostsblock-launcher" "/etc/cron.monthly/hostsblock-launcher" <<<"${sudo_password}"
		sudo -Sp '' ln -sf "/usr/share/indicator-hostsblock/launcher" "/etc/cron.monthly/hostsblock-launcher" <<<"${sudo_password}"
		"/usr/share/indicator-hostsblock/restart-indicator"
	fi
	if echo $choice | grep "None" > /dev/null
	then
		notify-send "HostsBlock will not update automatically" -i gtk-dialog-info -t 1000 -u normal &
		sudo -Sp '' rm "/etc/cron.hourly/hostsblock-launcher" "/etc/cron.daily/hostsblock-launcher" "/etc/cron.weekly/hostsblock-launcher" "/etc/cron.monthly/hostsblock-launcher" <<<"${sudo_password}"
		"/usr/share/indicator-hostsblock/restart-indicator"
	fi
fi
}
menu
option
