#!/bin/bash
# options
menu(){
im="zenity --list --checklist --title=\"HostsBlock Viewer\" --text=\"<b>Select file(s) to view:</b>\" --width 500 --height 230"
im=$im" --column=\"☑\" --column \"Filename\" --column \"Location\" "
im=$im"FALSE \"hostsblock.conf(full)\" \"/usr/share/indicator-hostsblock/hostsblock.conf\" "
im=$im"FALSE \"hostsblock.conf(extract)\" \"/usr/share/indicator-hostsblock/hostsblock.conf\" "
im=$im"FALSE \"hostsblock.deny.list\" \"/usr/share/indicator-hostsblock/hostsblock.deny.list\" "
im=$im"FALSE \"hostsblock.allow.list\" \"/usr/share/indicator-hostsblock/hostsblock.allow.list\" "
im=$im"FALSE \"user.deny.list\" \"~/.local/share/indicator-hostsblock/user.deny.list\" "
im=$im"FALSE \"user.allow.list\" \"~/.local/share/indicator-hostsblock/user.allow.list\" "
}
option(){
choice=`echo $im | sh -`
if echo $choice | grep "hostsblock.conf(full)" > /dev/null
then
	zenity --text-info --filename="/usr/share/indicator-hostsblock/hostsblock.conf" --title="hostsblock.conf - full (view only)" --width 980 --height 680 &
fi
if echo $choice | grep "hostsblock.conf(extract)" > /dev/null
then
	cp "/usr/share/indicator-hostsblock/hostsblock.conf" "/tmp/extract-hostsblock.conf"
	sed -i "s/^# .*$//g" "/tmp/extract-hostsblock.conf"
	sed -i "s/^### .*$//g" "/tmp/extract-hostsblock.conf"
	sed -i "/^\s*$/d" "/tmp/extract-hostsblock.conf"
	sed -i "s/^##/\n##/g" "/tmp/extract-hostsblock.conf"
	zenity --text-info --filename="/tmp/extract-hostsblock.conf" --title="hostsblock.conf - extract (view only)" --width 980 --height 680 &
fi
if echo $choice | grep "hostsblock.deny.list" > /dev/null
then
	zenity --text-info --filename="/usr/share/indicator-hostsblock/hostsblock.deny.list" --title="hostsblock.deny.list (view only)" --width 300 --height 600 &
fi
if echo $choice | grep "hostsblock.allow.list" > /dev/null
then
	zenity --text-info --filename="/usr/share/indicator-hostsblock/hostsblock.allow.list" --title="hostsblock.allow.list (view only)" --width 300 --height 600 &
fi
if echo $choice | grep "user.deny.list" > /dev/null
then
	if [ -f "$HOME/.local/share/indicator-hostsblock/user.deny.list" ]
	then
		zenity --text-info --filename="$HOME/.local/share/indicator-hostsblock/user.deny.list" --title="user.deny.list (view only)" --width 300 --height 600 &
	else
		notify-send "user.deny.list does not exist" -i gtk-dialog-info -t 1000 -u normal &
	fi
fi
if echo $choice | grep "user.allow.list" > /dev/null
then
	if [ -f "$HOME/.local/share/indicator-hostsblock/user.allow.list" ]
	then
		zenity --text-info --filename="$HOME/.local/share/indicator-hostsblock/user.allow.list" --title="user.allow.list (view only)" --width 300 --height 600 &
	else
		notify-send "user.allow.list does not exist" -i gtk-dialog-info -t 1000 -u normal &
	fi
fi
}
menu
option
